version: "3.7"


networks: 
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8100:80"
            - "8143:443"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel
    
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks: 
            - laravel
        
    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: dev 
            MYSQL_USER: dev    
            MYSQL_PASSWORD: dev
            MYSQL_ROOT_PASSWORD: dev
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
    
    composer: 
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel

    npm: 
        image: node:alpine3.12
        container_name: npm
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel
    
    artisan:
        build: 
            context: .
        container_name: artisan
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - php
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        container_name: phpmyadmin
        depends_on: 
            - mysql
        ports: 
            - "8101:80"
        environment: 
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: dev
        networks: 
            - laravel